// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsQlvoqs9m6Le78QjvIypL1jx7aKmpqtg',
    appId: '1:807844303698:web:73f071a1beeba6d853208b',
    messagingSenderId: '807844303698',
    projectId: 'instagram-tutorial-56e03',
    authDomain: 'instagram-tutorial-56e03.firebaseapp.com',
    storageBucket: 'instagram-tutorial-56e03.appspot.com',
    measurementId: 'G-7LXDNRGD97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADB1yEkF3d-KWP5TYBRxd5I30qA8tso78',
    appId: '1:807844303698:android:746aed06497c6a3a53208b',
    messagingSenderId: '807844303698',
    projectId: 'instagram-tutorial-56e03',
    storageBucket: 'instagram-tutorial-56e03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPzOZ0nQFoZDltZeVpffIW6kbpVb-IFWs',
    appId: '1:807844303698:ios:ad59d1287cfa420b53208b',
    messagingSenderId: '807844303698',
    projectId: 'instagram-tutorial-56e03',
    storageBucket: 'instagram-tutorial-56e03.appspot.com',
    iosBundleId: 'com.example.instagramTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPzOZ0nQFoZDltZeVpffIW6kbpVb-IFWs',
    appId: '1:807844303698:ios:57eb5a187dbb6d7953208b',
    messagingSenderId: '807844303698',
    projectId: 'instagram-tutorial-56e03',
    storageBucket: 'instagram-tutorial-56e03.appspot.com',
    iosBundleId: 'com.example.instagramTutorial.RunnerTests',
  );
}
